version: '3'

services:
  tts:
    image: ghcr.io/coqui-ai/tts-cpu
    ports:
      - "5002:5002"
    entrypoint: /bin/bash
    stdin_open: true # equivalent to -i
    tty: true       # equivalent to -t
